// JOB INITAPES
/* write some tape marks on tapes and rewind so 
/* they hay something written in it if they were empty
// LISTIO SYS
// LISTIO PROG
// MTC   REW,SYS000
// MTC   WTM,SYS000
// MTC   WTM,SYS000
// MTC   REW,SYS000
// MTC   REW,SYS001
// MTC   WTM,SYS001
// MTC   WTM,SYS001
// MTC   REW,SYS001
// MTC   REW,SYS002
// MTC   WTM,SYS002
// MTC   WTM,SYS002
// MTC   REW,SYS002
// MTC   REW,SYS003
// MTC   WTM,SYS003
// MTC   WTM,SYS003
// MTC   REW,SYS003
// EXEC  DSERV 
 DSPLYS ALL
/*
/&
// JOB SYSCMA
// OPTION LIST,LINK,DECK,CATAL
         ACTION MAP
// EXEC ASSEMBLY
         SUPVR SYSTEM=TAPE
         CONFG MODEL=30,SP=NO,DEC=YES,FP=NO,TIMER=YES,CHANSW=NO
         JCOPT DECK=YES,LIST=YES,LISTX=YES,SYM=YES,XREF=YES
         IOTAB NTP=4,MTP=8,PGR=5,TP=0,SPL=1,JIB=5,CHANQ=8  
** DEFAULT DEVICE DEFINITIONS
*  DEVICES ON CHANNEL 0
         DVCGEN CHUN=X'00A',DVCTYP=1442N1
         DVCGEN CHUN=X'00B',DVCTYP=1443
         DVCGEN CHUN=X'00D',DVCTYP=1442N1
         DVCGEN CHUN=X'01F',DVCTYP=1050A
*  DEVICES ON CHANNEL 1
         DVCGEN CHUN=X'0C0',DVCTYP=2400T9
         DVCGEN CHUN=X'0C1',DVCTYP=2400T9
         DVCGEN CHUN=X'0C2',DVCTYP=2400T9
         DVCGEN CHUN=X'0C3',DVCTYP=2400T9
         DVCGEN CHUN=X'0C4',DVCTYP=2400T9
         DVCGEN CHUN=X'0C5',DVCTYP=2400T9
** DEFAULT LOGICAL DEVICE ASSIGNMENTS 
         ASSGN SYSLOG,X'01F'
         ASSGN SYSRDR,X'00A'
         ASSGN SYSIPT,X'00A'
         ASSGN SYSPCH,X'00D'
         ASSGN SYSLST,X'00B'
         ASSGN SYS000,X'0C1'
         ASSGN SYS001,X'0C2'
         ASSGN SYS002,X'0C3'
         ASSGN SYS003,X'0C4'
         ASSGN SYS004,X'0C5'
         OPTION OC=YES,IT=YES,PC=YES
         PIOCS SELCH=YES,SETMOD=NO,RWTAU=NO     
         SEND  X'1800'
         END
/*
// EXEC LNKEDT
 INCLUDE IJALE
// EXEC LNKEDT
 INCLUDE IJQALL
// EXEC LNKEDT
 INCLUDE IJSCBL     COBOL-D COMPILER
// EXEC LNKEDT
 INCLUDE IJSDBG     DEBUG
// EXEC LNKEDT
 INCLUDE IJTFO
// EXEC LNKEDT
 INCLUDE IJASL2
// EXEC LNKEDT
 INCLUDE IJRPGSYS
// EXEC LNKEDT
 INCLUDE IJRRG
// EXEC LNKEDT
 INCLUDE IJPSM
// EXEC LNKEDT
// EXEC MAINT
/&
